### ISSUE TITLE
Update login and registration APIs and business logic

### ISSUE THREAD

**Issue by ricardobrg** [tiki/dashboard#127]
### Description

Update the APIs for the new login/registration flow.

### Tasks

- [ ] Update the cognito registration to request just email and password.
- [ ] Remove the post confirmation hook.
- [ ] Update the `profile` endpoint to match the profile form fields.
- [ ] Check if the user has a profile on login. If not, redirect to profile page.
